name: speakmate
description: "SpeakMate - AI English Speaking Coach"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  record: ^5.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  uuid: ^4.5.1
  path_provider: ^2.1.5
  flutter_dotenv: ^5.2.1
  audioplayers: ^6.1.0
  http: ^1.2.0
  flutter_tts: ^4.2.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
